version: "3.9"
services:
  react:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
